[package]
name = "ruda"
version = "0.1.0"
authors = ["Phosphorus15 <steepout@qq.com>"]
edition = "2018"

[dependencies]
llvm-sys = "38"
pest_derive = "2.0"
pest = "2.1.1"
docopt = "1.1.0"
serde = "1.0.101"
serde_derive = "1.0.101"