version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/rust
    steps:
      - checkout
      - cargo check
      - cargo test
      - cargo build
      - cargo build --release
