defaults: &defaults
  docker:
    - image: rust


version: 2
jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - cargo check
      - cargo test
      - cargo build
      - cargo build --release

workflows:
  version: 2
  test:
    jobs:
      - test
