version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: nwtgck/llvm:3.8.0
    steps:
      - checkout
      - run:
          command: sudo apt-get update; echo y | sudo apt install curl
      - run:
          command: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs > install.sh; sh install.sh -y;
      - run:
          command: echo 'export PATH=$HOME/.cargo/bin:$PATH' >> $BASH_ENV; echo 'export LLVM_SYS_38_PREFIX=/usr/local/llvm/llvm-3.8.0/' >> $BASH_ENV
      - run:
          command: cargo check
      - run:
          command: cargo test
      - run:
          command: cargo build
      - run:
          command: cargo build --release
